config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'greetings', to: 'greetings#index'

  resources 'posts', only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # by specifying resources :posts in config/routes.rb, Rails automatically creates the seven RESTful routes for the Post model

  # validations
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index
    @greetings = {
      english: english_greeting,
      spanish: spanish_greeting,
      french: french,
      german: german
    }
  end

  private

  def english_greeting
    "Hello, It's me!"
  end

  def spanish_greeting
    "Hola, soy yo!"
  end

  def french
    "Bonjour, c'est moi!"
  end

  def german
    "Hallo, ich bin es!"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = 'home sweet home!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @giphy_image_url = fetch_giphy_image(@post.title)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def fetch_giphy_image(query)
    if (api_key = ENV['GIPHY_API_KEY']).present?
      safe_query = CGI.escape(query)
      url = "https://api.giphy.com/v1/gifs/search?api_key=#{api_key}&q=#{safe_query}&rating=g&limit=1&offset=#{rand(1000)}"

      response = HTTParty.get(url)

      if response.code == 200 && response["data"].any?
        response["data"].sample["images"]["original"]["url"]
      else
        "https://media.giphy.com/media/26AHdRkxHMyHLV1u0/giphy.gif"
      end
    else
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExYnpxdnJ2dm9iam9zbGpmZzBlMHo1MmZjZndhN2Z2dWlzcW1vaTQwbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ALgyanclvTpPG/giphy.gif"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/greetings/index.html.erb
<h1>All The Greetings!</h1>

<% @greetings.each do |language, message| %>
  <p><strong><%= language.capitalize %>:</strong> <%= message %></p>
<% end %>

<%= link_to 'Back Home', root_path %>

app/views/home/index.html.erb
<h1>Welcome Home!</h1>
<p><%= @message %></p>
<%= link_to 'See Greetings', greetings_path %>
<br/>
<%= link_to 'See Posts', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speak To Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back Home', root_path %>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div class="errors" style="color: red;">
      <h2>Uhoh! There was an Error:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit "Create Post" %>
  </div>
<% end %>

<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<% if @giphy_image_url.present? %>
  <div>
    <img src="<%= @giphy_image_url %>" alt="Random Giphy" />
  </div>
<% end %>
<br/>
<%= link_to 'Back to Posts', posts_path %>